# Generated by Django 5.2.11 on 2026-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50, verbose_name="автор")),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_book",
                    models.CharField(max_length=100, verbose_name="название книги"),
                ),
                ("id_book", models.IntegerField(verbose_name="id жанра")),
                ("author_book", models.IntegerField(verbose_name="автор книги")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("uuid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_genre",
                    models.CharField(max_length=20, verbose_name="название жанра"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.IntegerField(verbose_name="жанр книги")),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.IntegerField(verbose_name="страницы")),
                ("uuid_book", models.IntegerField(verbose_name="uuid книги")),
            ],
        ),
        migrations.CreateModel(
            name="Shelving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelving", models.IntegerField(verbose_name="стелаж/шкаф")),
                ("shelf", models.IntegerField(verbose_name="полка")),
                ("uuid_book", models.IntegerField(verbose_name="uuid книги")),
            ],
        ),
    ]
