# Generated by Django 5.2.11 on 2026-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lib",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_lib",
                    models.CharField(max_length=100, verbose_name="название библиотек"),
                ),
                ("num_book", models.IntegerField(verbose_name="количество книг")),
                (
                    "addr",
                    models.CharField(max_length=100, verbose_name="адрес библиотеки"),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField()),
            ],
        ),
    ]
